const Quotes = [
	'"The only person you are destined to become is the person you decide to be." – Ralph Waldo Emerson',
	'"Once you learn to quit, it becomes a habit." ― Vince Lombardi Jr',
	'"A year from now you may wish you had started today." – Karen Lamb',
	'"The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion." - Arnold Schwarzenegger',
	'"Most people fail, not because of lack of desire, but, because of lack of commitment." – Vince Lombardi',
	'"Some people want it to happen, some wish it would happen, others make it happen." – Michael Jordan',
	'"All progress takes place outside the comfort zone." - Michal Joan Bobak',
	'"Tough times don’t last. Tough people do." – Robert H. Schuller',
	'"The only place where success comes before work is in the dictionary." - Vidal Sassoon',
	'"Our bodies are our gardens – our wills are our gardeners." – William Shakespeare',
	'"Reading is to the mind what exercise is to the body." - Joseph Addison',
	'"Whether you think you can, or you think you can’t, you’re right." – Henry Ford',
	'"Success is what comes after your stop making excuses." – Luis Galarza',
	'"The successful warrior is the average man, with laser-like focus." - Bruce Lee',
	'"Discipline is the bridge between goals and accomplishment." – Jim Rohn',
	'"You must expect great things of yourself before you can do them." - Michael Jordan',
	'"Get comfortable with being uncomfortable!" – Jillian Michaels',
	'"All our dreams can come true if we have the courage to pursue them." - Walt Disney',
	'"If something stands between you and your success, move it. Never be denied." - Dwayne Johnson',
	'"The purpose of training is to tighten up the slack, toughen the body, and polish the spirit." – Morihei Ueshiba',
	'"Today I will do what others won’t, so tomorrow I can accomplish what others can’t." — Jerry Rice',
	'"Confidence comes from discipline and training." – Robert Kiyosaki',
	'"We are what we repeatedly do. Excellence then is not an act but a habit." — Aristotle',
	'"You miss 100% of the shots you don’t take." — Wayne Gretzky',
	'"The difference between the impossible and the possible lies in a person’s determination." — Tommy Lasorda',
	'"You must do the thing you think you cannot do." – Eleanor Roosevelt',
	'"If you want something you’ve never had, you must be willing to do something you’ve never done." — Thomas Jefferson',
	'"The best way to gain self-confidence is to do what you are afraid to do." – Swati Sharma',
	'"There’s no secret formula. I lift heavy, work hard, and aim to be the best." – Ronnie Coleman',
	'"Nothing will work unless you do." — Maya Angelou',
	'"Our greatest glory is not in never failing, but in rising every time we fall." – Confucius',
	'"Strength does not come from physical capacity. It comes from an indomitable will." — Mahatma Gandhi',
	'"Don’t count the days, make the days count." — Muhammad Ali',
	'"All great achievements require time." — Maya Angelou',
	'"Every champion was once a contender that refused to give up." – Sylvester Stallone',
	'"Blood, sweat and respect. First two you give. Last one you earn." – The Rock',
	'"Everything negative - pressure, challenges - is all an opportunity for me to rise." - Kobe Bryant',
]

export default Quotes
